[2024-05-07 15:58:58,796] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T22:30:00+00:00 [queued]>
[2024-05-07 15:58:58,846] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T22:30:00+00:00 [queued]>
[2024-05-07 15:58:58,847] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:58:58,848] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:58:58,848] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:58:58,877] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-06 22:30:00+00:00
[2024-05-07 15:58:58,898] {standard_task_runner.py:52} INFO - Started process 3451 to run task
[2024-05-07 15:58:58,909] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'scheduled__2024-05-06T22:30:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmpq9plub2m', '--error-file', '/tmp/tmpd0x3xdjs']
[2024-05-07 15:58:58,915] {standard_task_runner.py:80} INFO - Job 98: Subtask run_spark
[2024-05-07 15:58:58,961] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-07 15:58:59,118] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T22:30:00+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:58:59,402] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T22:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-06T22:30:00+00:00
[2024-05-07 15:58:59,408] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:58:59,411] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:58:59,460] {subprocess.py:85} INFO - Output:
[2024-05-07 15:58:59,816] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:58:59,840] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:59:00,002] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:59:00,009] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240506T223000, start_date=20240507T155858, end_date=20240507T155900
[2024-05-07 15:59:00,057] {standard_task_runner.py:97} ERROR - Failed to execute job 98 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3451)
[2024-05-07 15:59:00,086] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:59:00,435] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
